name: iOS CI

on: pull_request

jobs:
  build:

    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Pod install
        run: ./gradlew podInstall

      - name: Build iOS app
        run: xcodebuild -workspace iosApp/iosApp.xcworkspace -scheme iosApp -configuration Debug -sdk iphonesimulator