name: iOS CI

on: pull_request

jobs:
  build:

    runs-on: macos-14

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app

      - name: Generate dummy framework
        run: ./gradlew :composeApp:generateDummyFramework

      - name: Install Pods
        run: ./gradlew podInstall

      - name: Build iOS app
        run: |
          xcodebuild \
            -workspace iosApp/iosApp.xcworkspace \
            -scheme iosApp \
            -configuration Debug \
            -sdk iphonesimulator